### ISSUE TITLE
Clarify/Change project license

### ISSUE THREAD

**Issue by Mingun** [Mingun/JHexView#1]
@sporst, @Argent77 thanks you both for this excellent library. I believe, it can live long alone with other projects, but for this licensing status need to be clarified.

@sporst, when you create library, you only add https://github.com/sporst/JHexView/blob/master/gpl.txt and https://github.com/sporst/JHexView/blob/master/readme.txt, which say the library is distributed under GPL-2.0 license. However, it is implicit from this context whether you meant "only GPL-2.0" license or "GPL-2.0 or later".

From a legal point of view, there are some differences that make it impossible to use this wonderful library in some projects in which I would like to use it (see https://github.com/kaitai-io/kaitai_struct_gui/pull/11), if it distributed on "only GPL-2.0" basis. See table at https://www.gnu.org/licenses/gpl-faq.en.html#AllCompatibility for license compatibility

Even if that is true, I would ask you and @Argent77 (who three, with me, made commits to this library) to consider changing the library license for the next release to "GPL-2.0 or later" or even "LGPL-2.1 or later", because LGPL family more suitable for libraries, as noted also in GPL.

I think this will benefit the library because allowing it to be used in commercial projects can expand its application boundaries (for example, my company has an internal log parser utility where it would be very useful, but unfortunately, we cannot use it because of the license). But even using "GPL-2.0 or later" will be better than GPL-2.0 because most GPL projects prefer to use GPL-3.0 ([99,484 java repositories](https://github.com/search?l=Java&q=license%3Agpl-3.0&type=Repositories) with GPL-3.0 against [27,866 java repositories with GPL-2.0](https://github.com/search?l=Java&q=license%3Agpl-2.0&type=Repositories) according to GitHub).

To change a project license, you need the consent of all participants who made changes to the project. These are 3 persons:

- [x] @sporst
- [x] @Argent77
- [x] @Mingun 

So if you all agree, we will change the license to one of those offered or suggested by you

**Comment by GreyCat** [comment]
You might want to reach out to the original authors by e-mail, if that's possible?

**Comment by Mingun** [comment]
Yeah, I'll do that. First I have to let people respond in the usual manner. Maybe they'll only be free on the weekend

**Comment by Argent77** [comment]
@Mingun I agree to a license change. A more liberal license, such as the LGPL, would greatly benefit the projects in which this library is currently used.

**Comment by Mingun** [comment]
Thanks, @Argent77 ! @sporst, we are awaiting your decision.

**Comment by sporst** [comment]
Sure, that's cool. Good luck using the library!

**Comment by Mingun** [comment]
Thanks, @sporst ! I'll change license to "LGPL-2.1 or later" in next release 2.0 (which I'll release in next couple days).

**Comment by GreyCat** [comment]
Sounds good, thank you, folks!

**Comment by Mingun** [comment]
[Release 2.0 on air!](https://github.com/Mingun/JHexView/releases/tag/v2.0). New license and API changes in prepare to multi-interval selections (in 2.1)

**Comment by GreyCat** [comment]
That's awesome, thanks! Could you also update https://github.com/kaitai-io/kaitai_struct_gui/pull/11 to use release 2.0?

**Comment by Mingun** [comment]
@GreyCat , of course. I'll do that on the weekend. Also I have plans to release 2.1 with the ability to select many regions at once first, to reflect that ability in **Kaitai Struct Gui** tree. Whether I have had time to release version 2.1 or not, I'll update PR.
